# Generated by Django 4.2.7 on 2023-12-11 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('countryName', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('countryCode', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='capital',
            fields=[
                ('capitalName', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('countryName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.country')),
            ],
        ),
    ]
